apiVersion: v1
kind: Pod
metadata:
  name: helloworld
spec:
  containers:
  - image: microsoft/aci-helloworld
    imagePullPolicy: Always
    name: helloworld
    resources:
      requests:
        memory: 100M # succeeds. kubectl shows 100M
        # memory: 0.1G # succeeds. kubectl describe shows 100M
        # memory: 100MB # can't deploy via k8s
        # memory: 100Mi # fails 0.1048576
        # memory: 1G # succeeds
        cpu: 1
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
    - containerPort: 443
      name: https
  dnsPolicy: ClusterFirst
  nodeName: virtual-kubelet-vampk8s-aci-linux
  # tolerations:
  #  - key: azure.com/aci
  #    effect: NoSchedule